name: Unzip Source Code

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Unzip Files
        run: |
          sudo apt-get install -y unzip
          unzip -o gonurse-source.zip -d .
          rm -f gonurse-source.zip

      - name: Commit & Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Unzipped project files automatically"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
